// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zunxdbtetzgqnkzvqmbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bnhkYnRldHpncW5renZxbWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDE1OTEsImV4cCI6MjA3MTk3NzU5MX0.oZ8eUJaiuJqL6k3MKbn_YT1k3QYfgW-_kLxBsaTo3Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});